# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WXOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(blank=True, max_length=300, verbose_name=b'\xe5\x86\x85\xe9\x83\xa8\xe5\xbe\xae\xe4\xbf\xa1\xe8\xae\xa2\xe5\x8d\x95\xe5\x8f\xb7')),
                ('transaction_id', models.CharField(blank=True, max_length=300, verbose_name=b'\xe5\xbe\xae\xe4\xbf\xa1\xe6\x94\xaf\xe4\xbb\x98\xe8\xae\xa2\xe5\x8d\x95\xe5\x8f\xb7')),
                ('time_end', models.CharField(blank=True, max_length=300, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe5\xae\x8c\xe6\x88\x90\xe6\x97\xb6\xe9\x97\xb4')),
                ('total_fee', models.CharField(blank=True, max_length=300, verbose_name=b'\xe6\x80\xbb\xe9\x87\x91\xe9\xa2\x9d')),
                ('openid', models.CharField(blank=True, max_length=300, verbose_name=b'\xe4\xbb\x98\xe6\xac\xbe\xe4\xba\xbaopenid')),
                ('trade_type', models.CharField(blank=True, max_length=300, verbose_name=b'\xe4\xba\xa4\xe6\x98\x93\xe7\xb1\xbb\xe5\x9e\x8b')),
                ('result_code', models.CharField(blank=True, max_length=300, verbose_name=b'\xe4\xb8\x9a\xe5\x8a\xa1\xe7\xbb\x93\xe6\x9e\x9c')),
                ('detail', models.TextField(blank=True, verbose_name=b'\xe8\xaf\xa6\xe7\xbb\x86')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True, verbose_name=b'\xe8\xae\xb0\xe5\xbd\x95\xe5\x88\x9b\xe5\xbb\xba\xe6\x97\xb6\xe9\x97\xb4')),
                ('last_update_time', models.DateTimeField(auto_now=True, null=True, verbose_name=b'\xe8\xae\xb0\xe5\xbd\x95\xe6\x9c\x80\xe5\x90\x8e\xe4\xbf\xae\xe6\x94\xb9\xe6\x97\xb6\xe9\x97\xb4')),
                ('pay', models.CharField(blank=True, max_length=100, verbose_name=b'\xe6\x94\xaf\xe4\xbb\x98\xe6\x83\x85\xe5\x86\xb5')),
                ('confirmed', models.BooleanField(default=False, verbose_name=b'\xe6\x98\xaf\xe5\x90\xa6\xe7\xa1\xae\xe8\xae\xa4')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
