# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wxorder',
            name='body',
            field=models.CharField(blank=True, max_length=300, verbose_name=b'\xe5\xae\x9e\xe9\x99\x85\xe5\x95\x86\xe5\x93\x81\xe5\x90\x8d\xe7\xa7\xb0'),
        ),
    ]
